const SuppliersStock =[
    {
        code: 1,
        name: "ali",
        phone : 3132216500,
        email : "ali@gmail.com",
        city :"jhang",
        taxnumber : 234,
        totalsaledue: 34500,
        totalsalereturndue : 4300
    },
    {
        code: 2,
        name: "ali",
        phone : 313224455,
        email : "ali@gmail.com",
        city :"jhang",
        taxnumber : 234,
        totalsaledue: 34500,
        totalsalereturndue : 4300,
    },
    {
        code: 3,
        name: "ali",
        phone : 313224455,
        email : "ali@gmail.com",
        city :"jhang",
        taxnumber : 234,
        totalsaledue: 34500,
        totalsalereturndue : 4300,
    },
    {
        code: 4,
        name: "ali",
        phone : 313224455,
        email : "ali@gmail.com",
        city :"jhang",
        taxnumber : 234,
        totalsaledue: 34500,
        totalsalereturndue : 4300,
    },
    {
        code: 5,
        name: "ali",
        phone : 313224455,
        email : "ali@gmail.com",
        city :"jhang",
        taxnumber : 234,
        totalsaledue: 34500,
        totalsalereturndue : 4300,
    },
    {
        code: 6,
        name: "ali",
        phone : 313224455,
        email : "ali@gmail.com",
        city :"jhang",
        taxnumber : 234,
        totalsaledue: 34500,
        totalsalereturndue : 4300,
    },
    {
        code: 7,
        name: "ali",
        phone : 313224455,
        email : "ali@gmail.com",
        city :"jhang",
        taxnumber : 234,
        totalsaledue: 34500,
        totalsalereturndue : 4300,
    },
   
]

export default SuppliersStock;